# 项目相关配置文件

# Mysql相关配置文件
[database]
    [[database.default]]
        host     = "localhost"
        port     = "3306"
        user     = "root"
        pass     = "root"
        name     = "go_admin"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"

# Redis数据库配置
[redis]
    disk  = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,1"

[mongodb]
	[[mongodb.default]]
		address = "10.1.2.6:27017"
		database =  "admin"
		source =  "admin"
		username = "admin"
		password = "admin"
		poollimit = 1000
		timeout = 3


